### ISSUE TITLE
Aṣṭāṅgasaṃgraha Sū.36.5

### ISSUE THREAD

**Issue by vitus-a** [sarit/SARIT-corpus#104]
"saumyāg**r**eyaṃ" should be "saumyāg**n**eyaṃ" near the end of the second line of AS 1.36.5 (5th line in Athavale's edition, see below).

![grafik](https://user-images.githubusercontent.com/25415004/68125403-d5eb3800-ff11-11e9-86e3-63af7ade0309.png)

**Comment by wujastyk** [comment]
Thanks Vitus, I've updated the XML file at Github
<https://github.com/sarit/SARIT-corpus>.  It will take a little time before
the updated file is loaded by Patrick into the public version of SARIT.

The procedure I I used, which is also open to you, is as follows.

   1. I have "forked" the Github SARIT collection.  That means, I have a
   personal copy of the whole thing.  That's at Github, and also on my local
   hard drive.
   2. I make changes to my personal files on my computer.  I then run "git
   commit -a" to register changes with git.  Then I run "git push" which
   uploads the changed files from my machine to Github in the web.
   3. I go to Github, and I issue a "pull request" for that changed file.
   That means, I am requesting that my personal changes should be merged into
   the master version of the SARIT files.  After that, if everyone agrees, my
   personal change is written into the master version of the SARIT file at
   Github.

It takes time to write out these steps, but in practice it's the work of a
minute or two.  But it keeps everything in good order.

If you want to be able to make changes yourself, start by forking the SARIT
collection.  Then you can experiment without any risks to the main
repository.

Best, and many thanks,
Dominik


--
Professor Dominik Wujastyk <http://ualberta.academia.edu/DominikWujastyk>
,

Singhmar Chair in Classical Indian Society and Polity
,

Department of History and Classics <http://historyandclassics.ualberta.ca/>
,
University of Alberta, Canada
.

South Asia at the U of A:

sas.ualberta.ca
