### ISSUE TITLE
three typos in Ca.1.20.4

### ISSUE THREAD

**Issue by vitus-a** [sarit/SARIT-corpus#115]
sukhāni tu svalvāgantornakhadaśanapatanābhicārābhiśāpābhiṣaṅgābhighātavyadhabandhānaveṣṭanapīḍanarajjudahanaśastrāśanibhūtopasargādīni nijasya tu mukhaṃ vātapittaśleṣmaṇāṃ vaiṣamyam // 

should be:
**mukhāni** tu **khalv**āgantornakhadaśanapatanābhicārābhiśāpābhiṣaṅgābhighātavyadha**bandhana**veṣṭanapīḍanarajjudahanaśastrāśanibhūtopasargādīni nijasya tu mukhaṃ vātapittaśleṣmaṇāṃ vaiṣamyam // 

https://sarit.indology.info/sarit-pm/works/carakasamhita.xml?root=1.5.4.3.44&view=div#

![grafik](https://user-images.githubusercontent.com/25415004/119502223-fdab2680-bd69-11eb-8163-5cb5706f786a.png)

**Comment by paddymcall** [comment]
Thank you, fixed in #116
