### ISSUE TITLE
Missing text for Carakasaṃhitā Nidānasthāna 7

### ISSUE THREAD

**Issue by gennaios** [sarit/SARIT-corpus#121]
Hello,

From what I recall, this chapter is missing. I know not the reason. I found the Sanskrit text here; perhaps this is suitable (unless there is a specific reason for exclusion)?

https://www.carakasamhitaonline.com/index.php?title=Unmada_Nidana

**Comment by wujastyk** [comment]
You're absolutely right!  I didn't know 2.7 was missing.  Thank you for pointing it out!

I will fix this.  It's important to know, in this context, that the texts at SARIT are _editions_.  We aren't just scraping stuff off the internet (like carakasamhitaonline, which does have other virtues).  The SARIT texts are transcriptions that reproduce particular authoritative printed editions.  In this case, the famous 1941edition of Yadava Trikamji Acharya, published in Bombay.  So I'll track down that particular text and get the chapter 2.7 added in.

Thanks again!

**Comment by gennaios** [comment]
Terrific. Thank you. Yes I am aware all such texts are editions, and was unaware, or did not yet look carefully enough, to determine which.

Something I’ve been thinking about writing you about: concerning a critical edition or full translation of Caraka besides those available. I hope such occurs someday. While the availability of a shastra, e.g. a dharmashastra, may not all of a sudden give rise to those capable of comprehension, concerning the texts of Ayurveda, I think you understand the importance of such. More than what is happening now, freedom from all suffering and disease, immunity to everything known that I can think of, cultivation of mind memory intelligence well-being etc. through the accumulated expert tradition that is shastra, perhaps some future change in the entirety of how we think of dravya (all that is consumed), etc., a greater ability to pursue what is good, noble, etc. that existed perhaps among all spiritual-philosophical peoples, perhaps such will someday be possible. As Hindus consider this a dark age with what is possible and highest only a memory, so did the Ancient Greeks and Romans. What is happening now is a symptom of this lack of understanding and pursuit. Perhaps more availability of texts will help or is one of numerous conditions that may someday as they say set the stage.

As for the explanation of ojas, you may know the entirety of what we consume affects energy, mood, memory, mental clarity, etc. I think all such markers cannot be separated from any other; various systems are inter-related. As for the technical reasons for poor immunity, if one attempts to survey the decades of studies on plants and resistance to infection, I think one can conclude all considered essential nutrients have an effect on immunity, required nutrient levels are dynamic (as is water or sleep) and change with emotional or physical stress (exogenous too as with a bacteria or virus), required nutrient levels are closer to what has been found in paleolithic human fossils though I think such may be higher and intake levels of other hominids that eat “wild plants” may be our true need, and plants are as you know made up of much more than what is considered essential.

I do not know who learns Ayurveda according to the traditional method of guru, with 10–15+ years of learning various topics as would a Brahmin, and looks at the accumulated decades of studies on immunity. The diet of shastras, e.g. yava gavedukha or wild grains (I think such are best for those that do not need wheat or rice which are better suited to physical activity), wild greens (e.g. agastya mandukaparni kakamaci, …), flowers, whole ground seed (in place of oil), and the various other prescriptions one can find either in Ayurvedic texts, other shastras, or other Hindu texts, all such matters. Perhaps few attempt to maintain perfect balance of doshas, or consider dosha as fault or disease potentiality, much as Chinese medicine is no longer classical, e.g. seeking the Tao and perfect balance of yin and yang, yet perhaps greater philological examination of texts by those capable will show the world and even India itself that there is a higher knowledge.

**Comment by wujastyk** [comment]
Thank you for your comments, and I agree with you wholeheartedly.  I am a philologist and Sanskrit scholar, not trained in medicine.  But it is clear even to me that we could live better than we mostly do and that ayurveda contains some excellent ideas (and some terrible ones too :-).   

Perhaps you are aware of the [Caraka Project ](https://www.istb.univie.ac.at/caraka/index.html) at the U. of Vienna?  Efforts have stalled a little, but there has been a lot of work done on the philosophical aspects of Caraka, especially the Vimanasthana.

I started a project on Suśrutasaṃhtā, the [Sushruta Project](http://sushrutaproject.org).  The website explains what we're doing and makes everything available. 

Best,
Dominik

**Comment by gennaios** [comment]
Hello Dominik,

Someday I may try to contact you and perhaps such continued dialogue will prove fruitful in someway. 

Availability of texts or studies does not necessarily mean there will be those with the mind and will sufficient for decent understanding. As you know. E.g, when Caraka mentions balance of tissues, dhatusamya, as the main purpose of its shastra (and method of discourse), it takes much thought and study to know how to dynamically combine rasa, from all available foods, e.g leaf flower bitter astringent, to gain instinct of the effect of such on the entire body. Plus generally few have access to the classical foods now considered wild or weed that are far higher in nutrients, thus I think allow one to consume less food, to achieve such. Under such conditions I think rating once every one two or four days as said in the manusmriti I think is close to ideal for us not active like laborers farmers warriors etc. Yet many factors like vaidyas no longer learning in a manner similar to traditional Brahmins from an early age makes much difficult. Elsewhere, there are numerous studies concerning various foods such as flower leaf intact grain such as yava or gavedukha, or large traditional amounts of high antioxidant fruits such as those of the genera of triphala, and effect on many things including immunity and infection. Yet few perhaps are looking at all these things and then saying immunity and treatment perhaps of most or all conditions or infections might be possible. In general, such knowledge is quite scattered and debate and sources of learning are not as accessible as before. There perhaps is no more kuladharma and ganadharma. 

Yet I was thinking. As I think Caraka is the most encyclopedic text and I think the one that possibly may lead to a noble spirit akin to those of the Vedic age, perhaps someday finding the ability to pursue a complete translation is worthwhile. Perhaps you’ve already thought of such. Perhaps yourself or others such as Olivelle and others could convince some of the beef and include Ayurvedic texts in Murty.
