### ISSUE TITLE
Broken link in readme

### ISSUE THREAD

**Issue by lb42** [sarit/SARIT-corpus#68]
"The specific guidelines that are used for the SARIT corpus are here: http://sarit.indology.info/exist/apps/sarit/docs/encoding-guidelines.html "
This URL was not working this morning: see attached 
![sarit](https://user-images.githubusercontent.com/660724/28208881-dc0a3bd2-6887-11e7-8ef5-93e614fae1d3.png)

**Comment by paddymcall** [comment]
Thanks, closed in current devel branch
