### ISSUE TITLE
Carakasaṃhitā 1.7.50ab

### ISSUE THREAD

**Issue by vitus-a** [sarit/SARIT-corpus#97]
Ca.1.7.50ab vidhireṣa vikārāṇāmanutpatau
should be: vidhireṣa vikārāṇām anutpattau

**Comment by kellner** [comment]
And should that not be "vidhir eṣa vikārāṇām anutpattau"?

**Comment by paddymcall** [comment]
Thank you, typo in anutpattau is closed in a6cac42.  I chose not to split the words as suggested, the rest of the file is spaced ``devanāgarī style'' as well.
