### ISSUE TITLE
Arthaśāstra 1.7.1

### ISSUE THREAD

**Issue by vitus-a** [sarit/SARIT-corpus#98]
@paddymcall AŚ 1.7.1 should end with _artha.samyogena, hitena vṛttim_ (_, hitena_ is missing) - http://sarit.indology.info/apps/sarit-pm/works/kautalyarthasastra.xml?root=1.5.6.3.22

**Comment by paddymcall** [comment]
Thank you for pointing this out!  Is this line found in Kangle's edition (2nd edition, see header of the xml document)?  I do not have that book at hand.

**Comment by vitus-a** [comment]
I only have the 1st edition (1960) at hand, which reads as noted above.
